apiVersion: v1
kind: Namespace
metadata:
  name: sample-app
  labels:
    name: sample-app

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: banana-app
  namespace: sample-app
  labels:
    app: banana-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banana-app
  template:
    metadata:
      labels:
        app: banana-app
    spec:
      containers:
        - name: banana-app
          image: hashicorp/http-echo
          args:
            - "-text=banana"
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 50Mi
---
kind: Service
apiVersion: v1
metadata:
  name: banana-service
  namespace: sample-app
spec:
  selector:
    app: banana-app
  ports:
    - port: 5678 # Default port for image

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: apple-app
  namespace: sample-app
  labels:
    app: apple-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apple-app
  template:
    metadata:
      labels:
        app: apple-app
    spec:
      containers:
        - name: apple-app
          image: hashicorp/http-echo
          args:
            - "-text=apple"
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 50Mi
---
kind: Service
apiVersion: v1
metadata:
  name: apple-service
  namespace: sample-app
spec:
  selector:
    app: apple-app
  ports:
    - port: 5678 # Default port for image

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx-demo
  namespace: sample-app
spec:
  rules:
    - host: { { external_ip } }
      http:
        paths:
          - path: /apple
            pathType: Prefix
            backend:
              service:
                name: apple-service
                port:
                  number: 5678
          - path: /banana
            pathType: Prefix
            backend:
              service:
                name: banana-service
                port:
                  number: 5678
          - path: /broccoli
            pathType: Prefix
            backend:
              service:
                name: broccoli-service
                port:
                  number: 5678
  ingressClassName: nginx

---
kind: Service
apiVersion: v1
metadata:
  name: broccoli-service
  namespace: sample-app
spec:
  selector:
    app: broccoli-app
  ports:
    - port: 5678 # Default port for image

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: broccoli-app
  namespace: sample-app
  labels:
    app: broccoli-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broccoli-app
  template:
    metadata:
      labels:
        app: broccoli-app
    spec:
      containers:
        - name: broccoli-app
          image: hashicorp/http-echo
          args:
            - "-text=broccoli is the greatest of all fruits"
          resources:
            limits:
              cpu: 75m
              memory: 3400Ki
            requests:
              cpu: 50m
              memory: 3000Ki
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-generator
  namespace: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffic-generator
  template:
    metadata:
      labels:
        app: traffic-generator
    spec:
      containers:
        - name: traffic-generator
          image: ellerbrock/alpine-bash-curl-ssl
          command: ["/bin/bash"]
          args:
            [
              "-c",
              "while :; do curl http://{{external_ip}}/apple > /dev/null 2>&1; curl http://{{external_ip}}/banana > /dev/null 2>&1;curl http://{{external_ip}}/broccoli > /dev/null 2>&1;curl -s http://{{external_ip}}/broccoli; sleep 0.05; done",
            ]
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 50Mi
