name: Github Workflow Checks
on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:
permissions: write-all
jobs:
  regula:
    uses: ollionorg/centralized-workflows/.github/workflows/rego.yaml@main
    secrets: inherit
  terraform:
    uses: ollionorg/centralized-workflows/.github/workflows/terraform-aws.yaml@main
    secrets: inherit
